### ISSUE TITLE
Page 495, 7. => CurrentDirectory,

### ISSUE THREAD

**Issue by centpede** [markjprice/cs12dotnet8#11]
Dear Mark,

possibly 

`string path = Combine(CurrentDirectory, "people.xml");`

should be changed to

`string path = Combine(Directory.GetCurrentDirectory(), "people.xml");`

The same on page 499, 3.

Thanks,
Robin

**Comment by markjprice** [comment]
The existing statement works correctly and is shorter so I don't know why you want to change it. Yours works too of course but it's longer.

**Comment by centpede** [comment]
Strange. I got an "CurrentDirectory ist unknown" error.

**Comment by markjprice** [comment]
`CurrentDirectory` is a property of the `Environment` static class that is imported in .NET 6 and later projects by default.
![image](https://github.com/markjprice/cs12dotnet8/assets/14040265/a0ebb272-65e7-438a-9f0d-6f3a9e8828ed)

**Comment by centpede** [comment]
You are right, I've overseen to include System.Environment from Page 493 /2., my fault, sorry!

**Comment by markjprice** [comment]
No worries. I suspect that other readers might too, it's easy to overlook because I do not show the actual markup because I was trying to save space in the book (I'm limited to about 750 pages). I've added an improvement item for this:
https://github.com/markjprice/cs12dotnet8/blob/main/docs/errata/improvements.md#page-493---serializing-as-xml
