### ISSUE TITLE
there is no the check box labeled "Do not use top-level statements" in Microsoft Visual Studio Enterprise 2022 

### ISSUE THREAD

**Issue by andremayers** [markjprice/cs12dotnet8#18]
I will appreciate an alternative, a quick one if possible. 
Otherwise, i enjoy the book until now

**Comment by markjprice** [comment]
Please tell me which page you are on, what section title you are in, and what step number you are trying to complete. Please also include a screenshot showing the missing check box. The reason is that the check box labeled "Do not use top-level statements" is context dependent i.e. it may or may not appear based on factors like what project type you are using. For example, a console app targetting .NET 8 has it:
![image](https://github.com/markjprice/cs12dotnet8/assets/14040265/07b4f5ad-a32b-48e3-a3d5-59e95ddd88b7)
But a console app targetting .NET 5 does not have it:
![image](https://github.com/markjprice/cs12dotnet8/assets/14040265/857b0db1-2865-46ca-88c7-d3f4a7c67384)
And a class library targetting .NET 8 dot not have it:
![image](https://github.com/markjprice/cs12dotnet8/assets/14040265/d8dbbbe2-5eb6-4ca6-8e3e-dd7909313ae0)

So just saying "there is no the check box labeled "Do not use top-level statements" in Microsoft Visual Studio Enterprise 2022" makes no sense.

**Comment by andremayers** [comment]
I am sorry. It was very clear in the book "Do NOT navigate to File | New | Project…". 
But I did it.
