### ISSUE TITLE
Page 299 - very minor change suggestion

### ISSUE THREAD

**Issue by rmantel23** [markjprice/cs12dotnet8#49]
in the 3rd bullet you write:

The baby object is added to the Children collection of both parents and then returned. Classes 
are reference types, meaning a reference to the baby object stored in memory is added, not a 
clone of the baby object. You will learn the difference between reference types and value types 
later in **Chapter 6, Implementing Interfaces and Inheriting Classes.**

But that's the chapter we are in, so maybe change to 'rhis chapter'.

**Comment by markjprice** [comment]
You might have guessed that this was caused by that section being at the end of Chapter 5 in earlier editions but was later moved to the start of Chapter 6. ;-)

If you'd ever consider being a Technical Reviewer for any of my future books, get in touch via email. Your attention to detail is excellent.
