### ISSUE TITLE
Q: Example page 79

### ISSUE THREAD

**Issue by centpede** [markjprice/cs12dotnet8#6]
Dear Mark,

Page 79, example at the bottom:

```
string json = $$"""
            {
            "first name": "{{person.Firstname}}",
            "age": "{{person.Age}}",
            "calculation": "{{{1 + 2}}}"
            }
            """;
```

Why does "calculation" 1+2 has three curly braces? It's working with two as well and I found no explanation why the example uses three.
Mistake or intentional?

Great book, I love it!

Thanks,
Robin

**Comment by markjprice** [comment]
It is intentional although maybe I need to add more explanation.

The following code is in the book:
```cs
var person = new { FirstName = "Alice", Age = 56 };

string json = $$"""
{
  "first_name": "{{person.FirstName}}",
  "age": {{person.Age}},
  "calculation": "{{{ 1 + 2 }}}"
}
""";

Console.WriteLine(json);
```
It produces the following output:
```
{
  "first_name": "Alice",
  "age": 56,
  "calculation": "{3}"
}
```
Note the braces around the 3.

If the code only used two braces then those are treated as a delimiter for the express `1 + 2` and do not appear in the output:
```cs
var person = new { FirstName = "Alice", Age = 56 };

string json = $$"""
{
  "first_name": "{{person.FirstName}}",
  "age": {{person.Age}},
  "calculation": "{{ 1 + 2 }}"
}
""";

Console.WriteLine(json);
```
Now it produces the following output:
```
{
  "first_name": "Alice",
  "age": 56,
  "calculation": "3"
}
```
Make sense?

**Comment by markjprice** [comment]
I have added an improvement item for this: https://github.com/markjprice/cs12dotnet8/blob/main/docs/errata/improvements.md#page-79---raw-interpolated-string-literals
